[project]
name = "easy-predict"
version = "0.1.0"
description = "Simple repository to train prediction models using WOMD dataset."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.9.7",
]
