SUBSAMPLE_SEQUENCE = 2  # e.g. 2 means 5 Hz instead of 10Hz sampling
NUM_HISTORY_FRAMES = 10 // SUBSAMPLE_SEQUENCE
NUM_FUTURE_FRAMES = 80 // SUBSAMPLE_SEQUENCE
SEQUENCE_LENGTH = NUM_HISTORY_FRAMES + NUM_FUTURE_FRAMES + 1
MAX_AGENTS_TO_PREDICT = 8


ROADGRAPH_TYPE_TO_IDX = {
    # for lane
    "TYPE_FREEWAY": 0,
    "TYPE_SURFACE_STREET": 1,
    "TYPE_BIKE_LANE": 2,
    # for roadline
    "TYPE_BROKEN_SINGLE_WHITE": 3,
    "TYPE_SOLID_SINGLE_WHITE": 4,
    "TYPE_SOLID_DOUBLE_WHITE": 5,
    "TYPE_BROKEN_SINGLE_YELLOW": 6,
    "TYPE_BROKEN_DOUBLE_YELLOW": 7,
    "TYPE_SOLID_SINGLE_YELLOW": 8,
    "TYPE_SOLID_DOUBLE_YELLOW": 9,
    "TYPE_PASSING_DOUBLE_YELLOW": 10,
    # for roadedge
    "TYPE_ROAD_EDGE_BOUNDARY": 11,
    "TYPE_ROAD_EDGE_MEDIAN": 12,
    # for stopsign
    "TYPE_STOP_SIGN": 13,
    # for crosswalk
    "TYPE_CROSSWALK": 14,
    # for speed bump
    "TYPE_SPEED_BUMP": 15,
}

IDX_TO_ROADGRAPH_TYPE = {idx: _type for _type, idx in ROADGRAPH_TYPE_TO_IDX.items()}

ROADGRAPH_TYPE_TO_COLOR = {
    "TYPE_FREEWAY": "gray",
    "TYPE_SURFACE_STREET": "gray",
    "TYPE_BIKE_LANE": "gray",
    "TYPE_BROKEN_SINGLE_WHITE": "white",
    "TYPE_SOLID_SINGLE_WHITE": "white",
    "TYPE_SOLID_DOUBLE_WHITE": "white",
    "TYPE_BROKEN_SINGLE_YELLOW": "yellow",
    "TYPE_BROKEN_DOUBLE_YELLOW": "yellow",
    "TYPE_SOLID_SINGLE_YELLOW": "yellow",
    "TYPE_SOLID_DOUBLE_YELLOW": "yellow",
    "TYPE_PASSING_DOUBLE_YELLOW": "yellow",
    "TYPE_ROAD_EDGE_BOUNDARY": "purple",
    "TYPE_ROAD_EDGE_MEDIAN": "purple",
    "TYPE_STOP_SIGN": "red",
    "TYPE_CROSSWALK": "orange",
    "TYPE_SPEED_BUMP": "blue",
}
