# Train arguments
max_epochs: 20
batch_size: 128
learning_rate: 0.0002
accumulate_grad_batches: 1

# Data arguments
train_with_tracks_to_predict: False # instead of 128 elements use 8, False is standard WOMD training
num_workers: 16

# Loss options
loss_tracks_to_predict_mask: True  # True is standard WOMD
loss_use_ego_vehicle_mask: False  # False is standard WOMD

# Model arguments
hidden_size: 128

