# Train arguments
max_epochs: 500
batch_size: 64
val_batch_size: 8 # validation works with scenes and we can only fit 8 scenes in the GPU
accumulate_grad_batches: 1
learning_rate: 0.001
weight_decay: 0.01
grad_norm_clip: 5.0
eta_min: 1.0E-5

# Data arguments
train_dataset: data/processed/training.h5
val_dataset: data/processed/validation.h5
num_workers: 16

data_perturb:
  anchor_frame:
    perturb_prob: 0.0
  base_frame: 
    perturb_prob: 0.0
    delta_t: 10.0
    delta_yaw: 0.8
    
model_config:
  decoder:
    input_size: 12   #(x, y, c, s, v, extent, type_ohe)
    output_size: 2  #(accel, yaw_rate)
  dynamics_layer:
    max_acc: 10.0
    max_yaw_rate: 1.0
    delta_t: 0.2
  tl_encoder:
    use_tl_encoder: True 
    input_size: 11
    
# Model arguments
hidden_size: 128
