# Train arguments
max_epochs: 30
batch_size: 128
accumulate_grad_batches: 1
learning_rate: 0.0002
weight_decay: 0.01
grad_norm_clip: 1000.0
eta_min: 1.0E-5

# Data arguments
train_dataset: data/training.h5
val_dataset: data/validation_new.h5
train_with_tracks_to_predict: False # instead of 128 elements use 8, False is standard WOMD training
num_workers: 16

# Loss options
loss_tracks_to_predict_mask: True  # True is standard WOMD
loss_use_ego_vehicle_mask: False  # False is standard WOMD

# Model arguments
hidden_size: 128
