# Train arguments
data_module:
  train_dataset: data/pickled_1_3_0/validation
  val_dataset: data/pickled_1_3_0/validation
  
  batch_size: 48
  val_batch_size: 8 # validation works with scenes and we can only fit 8 scenes in the GPU
  num_workers: 32

max_epochs: 500
accumulate_grad_batches: 1
grad_norm_clip: 5.0
weight_decay: 0.01
learning_rate: 0.001

# For visualization
viz_scenario_offset: 10 # The scenario offset to start the visualization dataloader from 
viz_num_scenarios: 5 # The number of scenarios to visualize


data_perturb:
  anchor_frame:
    perturb_prob: 0.0
  base_frame: 
    perturb_prob: 0.0
    delta_t: 10.0
    delta_yaw: 0.8
    
model_config:
  decoder:
    input_size: 12   #(x, y, c, s, v, extent, type_ohe)
    output_size: 2  #(accel, yaw_rate)
  dynamics_layer:
    max_acc: 10.0
    max_yaw_rate: 1.0
    delta_t: 0.2
  tl_encoder:
    input_size: 11
  
  # TODO put map input size here
    
# Model arguments
hidden_size: 128
