# Train arguments
data_module:
  train_dataset: data/pickled_1_3_0/validation
  val_dataset: data/pickled_1_3_0/validation
  
  batch_size: 48
  val_batch_size: 8 # validation works with scenes and we can only fit 8 scenes in the GPU
  num_workers: 32

max_epochs: 500
accumulate_grad_batches: 1
grad_norm_clip: 5.0
weight_decay: 0.01
learning_rate: 0.001

# For visualization
viz_scenario_offset: 10 # The scenario offset to start the visualization dataloader from 
viz_num_scenarios: 5 # The number of scenarios to visualize

model_config:
  # Main hidden size shared across the model, this is the main parameter to
  # change model size
  hidden_size: 128
  actor_input_size: 12   #(x, y, c, s, v, extent, type_ohe)

  self_attention:
    n_heads: 8
    dropout_p: 0.0
   
  encoder:
    map_input_size: 25
    tl_input_size: 11
    
    # PointNet encoder parameters, the hyperparameters are shared across
    # actor, map and tl encoders but the networks are separate.
    point_net: 
      num_layers: 5    
      num_pre_layers: 3
      

  decoder:
    output_size: 2  #(accel, yaw_rate)

    dynamics_layer:
      max_acc: 10.0
      max_yaw_rate: 1.0
      delta_t: 0.2

    cross_attention:
      n_heads: 8  
      dropout_p: 0.0
    
    
